
AWSTemplateFormatVersion: 2010-09-09
Description: Simple cloundformation template of devOps class
# Metadata: 

Parameters: 
  env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stag
      - prod
  project:
    Type: String
    Default: demo
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small

# Mappings: 

# Conditions: 

Resources:
  myInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: learn-keypair
      ImageId: ami-0750a20e9959e44ff
      InstanceType: t2.micro
      SecurityGroupIds: [!Ref PublicSecurityGroup]
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref project, !Ref env, !Ref InstanceType]]
        - Key: project
          Value: !Ref project
        - Key: env
          Value: !Ref env
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: day5-public-sg
      GroupDescription: day5-public-sg
      VpcId: vpc-08a706cc8f8a601ec
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref project, !Ref env, !Ref InstanceType]]
        - Key: project
          Value: !Ref project
        - Key: env
          Value: !Ref env

Outputs:
  PublicIP:
    Value: !GetAtt myInstance.PublicIp
